export interface LongImageMessage {
  role: "user" | "assistant";
  content: string;
  modelName?: string;
}

export async function generateLongImage(
  messages: LongImageMessage[],
  title?: string,
): Promise<string> {
  const canvas = document.createElement("canvas");
  const ctx = canvas.getContext("2d");
  if (!ctx) throw new Error("Canvas not supported");

  const width = 800;
  const padding = 40;
  const cardPadding = 20;
  const cardSpacing = 16;
  const maxTextWidth = width - padding * 2 - cardPadding * 2;
  const lineHeight = 24;
  const titleHeight = title ? 60 : 0;
  const watermarkHeight = 40;

  const measureMessage = (msg: LongImageMessage) => {
    ctx.font = "14px sans-serif";
    const lines = wrapText(ctx, msg.content, maxTextWidth);
    const labelHeight = 24;
    return labelHeight + lines.length * lineHeight + cardPadding * 2;
  };

  const totalHeight =
    padding +
    titleHeight +
    messages.reduce((sum, msg) => sum + measureMessage(msg) + cardSpacing, 0) +
    watermarkHeight +
    padding;

  canvas.width = width;
  canvas.height = totalHeight;

  ctx.fillStyle = "#0a0a0a";
  ctx.fillRect(0, 0, width, totalHeight);

  let y = padding;

  if (title) {
    ctx.fillStyle = "#e5e5e5";
    ctx.font = "bold 20px sans-serif";
    ctx.fillText(title, padding, y + 30);
    y += titleHeight;
  }

  for (const msg of messages) {
    ctx.font = "14px sans-serif";
    const lines = wrapText(ctx, msg.content, maxTextWidth);
    const cardHeight = 24 + lines.length * lineHeight + cardPadding * 2;
    const cardY = y;
    const cardX = padding;
    const cardW = width - padding * 2;

    ctx.fillStyle = msg.role === "user" ? "#1a1a2e" : "#16201a";
    roundRect(ctx, cardX, cardY, cardW, cardHeight, 8);
    ctx.fill();

    ctx.fillStyle = msg.role === "user" ? "#8888cc" : "#66aa66";
    ctx.font = "bold 13px sans-serif";
    const label = msg.role === "user" ? "User" : (msg.modelName || "Assistant");
    ctx.fillText(label, cardX + cardPadding, cardY + cardPadding + 16);

    ctx.fillStyle = "#d4d4d4";
    ctx.font = "14px sans-serif";
    let textY = cardY + cardPadding + 40;
    for (const line of lines) {
      ctx.fillText(line, cardX + cardPadding, textY);
      textY += lineHeight;
    }

    y += cardHeight + cardSpacing;
  }

  ctx.fillStyle = "#666";
  ctx.font = "12px sans-serif";
  ctx.fillText("Generated by DEEIX Chat", padding, totalHeight - padding);

  return canvas.toDataURL("image/png");
}

function wrapText(
  ctx: CanvasRenderingContext2D,
  text: string,
  maxWidth: number,
): string[] {
  const paragraphs = text.split("\n");
  const lines: string[] = [];
  for (const para of paragraphs) {
    const words = para.split("");
    let currentLine = "";
    for (const char of words) {
      const testLine = currentLine + char;
      if (ctx.measureText(testLine).width > maxWidth && currentLine) {
        lines.push(currentLine);
        currentLine = char;
      } else {
        currentLine = testLine;
      }
    }
    lines.push(currentLine || " ");
  }
  return lines;
}

function roundRect(
  ctx: CanvasRenderingContext2D,
  x: number,
  y: number,
  w: number,
  h: number,
  r: number,
) {
  ctx.beginPath();
  ctx.moveTo(x + r, y);
  ctx.lineTo(x + w - r, y);
  ctx.quadraticCurveTo(x + w, y, x + w, y + r);
  ctx.lineTo(x + w, y + h - r);
  ctx.quadraticCurveTo(x + w, y + h, x + w - r, y + h);
  ctx.lineTo(x + r, y + h);
  ctx.quadraticCurveTo(x, y + h, x, y + h - r);
  ctx.lineTo(x, y + r);
  ctx.quadraticCurveTo(x, y, x + r, y);
  ctx.closePath();
}

export function downloadDataUrl(dataUrl: string, filename: string) {
  const link = document.createElement("a");
  link.download = filename;
  link.href = dataUrl;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
}
